In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [2]:
data = pd.read_csv('weather.csv')

In [3]:
data.columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [4]:
data.head

<bound method NDFrame.head of      MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW
1       14.0     26.9       3.6          4.4       9.7         ENE
2       13.7     23.4       3.6          5.8       3.3          NW
3       13.3     15.5      39.8          7.2       9.1          NW
4        7.6     16.1       2.8          5.6      10.6         SSE
..       ...      ...       ...          ...       ...         ...
361      9.0     30.7       0.0          7.6      12.1         NNW
362      7.1     28.4       0.0         11.6      12.7           N
363     12.5     19.9       0.0          8.4       5.3         ESE
364     12.5     26.9       0.0          5.0       7.1          NW
365     12.3     30.2       0.0          6.0      12.6          NW

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0             30.0         SW         NW           6.0  ...           29
1             39.0          E          W           4.0  ...           36
2             85.0          N        NNE           6.0  ...           69
3             54.0        WNW          W          30.0  ...           56
4             50.0        SSE        ESE          20.0  ...           49
..             ...        ...        ...           ...  ...          ...
361           76.0        SSE         NW           7.0  ...           15
362           48.0        NNW        NNW           2.0  ...           22
363           43.0        ENE        ENE          11.0  ...           47
364           46.0        SSW        WNW           6.0  ...           39
365           78.0         NW        WNW          31.0  ...           13

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0         1019.7       1015.0         7         7     14.4     23.6
1         1012.4       1008.4         5         3     17.5     25.7
2         1009.5       1007.2         8         7     15.4     20.2
3         1005.5       1007.0         2         7     13.5     14.1
4         1018.3       1018.5         7         7     11.1     15.4
..           ...          ...       ...       ...      ...      ...
361       1016.1       1010.8         1         3     20.4     30.0
362       1020.0       1016.9         0         1     17.2     28.2
363       1024.0       1022.8         3         2     14.5     18.3
364       1021.0       1016.2         6         7     15.8     25.9
365       1009.6       1009.2         1         1     23.8     28.6

     RainToday  RISK_MM RainTomorrow
0           No      3.6          Yes
1          Yes      3.6          Yes
2          Yes     39.8          Yes
3          Yes      2.8          Yes
4          Yes      0.0           No
..         ...      ...          ...
361         No      0.0           No
362         No      0.0           No
363         No      0.0           No
364         No      0.0           No
365         No      0.0           No

[366 rows x 22 columns]>

In [5]:
data[data.isnull().any(axis=1)]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
113,12.7,28.6,6.6,3.2,8.6,W,50.0,NaN,W,NaN,...,42,1008.3,1002.3,5,5,16.5,27.4,Yes,0.0,No
118,11.7,27.6,0.0,7.8,8.1,W,48.0,NaN,W,NaN,...,25,1013.6,1009.1,2,6,17.6,26.8,No,0.0,No
127,10.8,29.2,0.0,8.4,7.5,E,50.0,NaN,ENE,NaN,...,34,1021.6,1017.7,0,7,17.5,27.7,No,3.0,Yes
138,12.5,29.9,0.0,5.8,10.7,NW,43.0,NaN,WNW,0.0,...,30,1022.7,1018.8,0,1,16.8,29.2,No,0.0,No
140,11.5,29.3,0.0,5.2,8.0,NW,46.0,NaN,WSW,0.0,...,35,1013.8,1009.4,7,7,17.1,27.6,No,0.0,No
174,7.5,19.0,0.0,4.0,6.8,ENE,26.0,NaN,ESE,0.0,...,43,1025.5,1022.2,6,5,12.6,18.1,No,0.0,No
176,5.0,20.9,0.0,2.0,8.9,WNW,22.0,NaN,NW,0.0,...,42,1019.9,1014.3,7,6,10.1,20.6,No,0.2,No
180,-2.1,13.8,0.2,1.8,9.5,NNW,22.0,NaN,NNW,0.0,...,40,1020.6,1019.6,0,1,6.3,13.2,No,0.0,No
189,-0.2,18.1,0.0,4.4,9.4,NW,24.0,NaN,NW,0.0,...,44,1021.4,1018.9,1,1,6.7,16.9,No,0.0,No
193,9.4,19.2,0.0,2.2,7.7,NaN,24.0,E,NNW,4.0,...,47,1024.2,1020.3,7,1,12.1,18.8,No,0.0,No
195,2.2,18.6,0.0,2.0,9.2,NNW,31.0,NaN,NNW,NaN,...,44,1024.4,1021.0,1,3,8.5,17.8,No,0.0,No
200,-2.7,18.1,0.0,2.2,9.3,W,52.0,NaN,WNW,0.0,...,36,1017.8,1014.3,1,1,3.5,16.7,No,0.0,No
208,4.9,18.1,5.2,1.2,8.5,NNW,22.0,NaN,NW,0.0,...,55,1025.7,1022.3,1,1,8.9,17.7,Yes,0.0,No
209,1.4,16.8,0.0,1.6,8.2,NW,20.0,NaN,NW,0.0,...,50,1027.2,1024.7,1,4,6.2,16.3,No,0.2,No
211,-0.1,18.0,0.0,2.0,8.6,NaN,NaN,N,NNW,2.0,...,46,1033.2,1028.7,1,1,5.6,17.4,No,0.0,No
212,-0.9,18.5,0.0,2.2,8.9,E,22.0,NaN,N,0.0,...,38,1030.2,1027.4,2,3,4.7,18.2,No,0.0,No
213,0.6,14.0,0.0,2.2,2.7,NE,17.0,NaN,ENE,NaN,...,67,1032.3,1028.9,7,7,4.6,13.9,No,0.0,No
221,7.4,16.3,0.0,1.2,NaN,NNE,30.0,SSE,NE,6.0,...,65,1031.4,1027.9,7,7,12.1,14.5,No,6.2,Yes
222,8.6,13.7,6.2,2.2,0.0,NW,31.0,E,NaN,2.0,...,94,1027.8,1024.3,8,8,10.3,11.6,Yes,4.8,Yes
237,4.3,12.6,0.0,2.0,9.0,NW,46.0,NaN,WNW,0.0,...,54,1026.3,1021.9,3,1,7.8,11.3,No,0.0,No
247,-0.1,14.2,0.0,1.4,7.0,W,13.0,NaN,WNW,NaN,...,55,1032.9,1028.9,1,2,4.7,12.6,No,0.0,No
249,3.0,11.1,0.8,1.4,0.2,W,35.0,NaN,N,0.0,...,96,1024.4,1021.1,7,8,6.3,8.6,No,16.8,Yes
250,2.9,9.5,16.8,1.4,6.5,NW,35.0,NaN,NW,0.0,...,72,1021.6,1019.6,6,6,5.5,7.4,Yes,0.0,No
255,0.5,11.0,0.0,1.0,0.9,NNW,31.0,NaN,NW,0.0,...,69,1024.4,1021.9,7,7,2.8,10.7,No,0.0,No
257,-1.7,13.6,0.0,1.8,5.2,NNW,28.0,NaN,NNW,NaN,...,46,1023.0,1020.1,1,7,3.9,13.3,No,0.2,No
259,-1.8,11.5,0.0,0.6,4.7,NNW,41.0,NaN,NNW,0.0,...,55,1019.7,1013.9,7,3,1.3,11.0,No,0.0,No
262,-1.1,11.0,0.2,1.8,0.0,WNW,41.0,NaN,NE,0.0,...,87,1014.4,1009.0,7,8,2.4,8.7,No,19.2,Yes
271,0.8,12.2,0.0,1.8,8.6,NaN,NaN,S,S,19.0,...,49,1020.9,1016.8,3,1,6.5,11.2,No,0.0,No
272,-2.8,12.2,0.0,2.6,8.7,NNW,31.0,NaN,NNW,0.0,...,48,1018.3,1014.6,1,1,2.7,11.5,No,0.0,No
273,-2.8,14.1,0.0,2.2,6.8,WNW,48.0,NaN,WNW,0.0,...,38,1017.3,1012.9,1,7,3.0,12.8,No,1.0,No
278,-1.9,10.9,0.0,1.8,4.2,S,50.0,NaN,SSW,0.0,...,72,1020.8,1019.2,3,8,5.5,7.2,No,4.0,Yes
299,-1.5,17.3,0.0,2.8,9.0,NW,48.0,NaN,WNW,0.0,...,23,1023.9,1020.3,5,7,4.8,15.8,No,0.0,No
300,-3.3,15.1,0.0,3.0,NaN,SSW,30.0,SSE,SE,9.0,...,23,1027.7,1025.5,1,1,7.9,14.4,No,0.0,No
302,-0.2,16.2,0.0,3.4,5.9,E,28.0,NaN,ENE,0.0,...,45,1027.6,1022.9,7,6,7.3,14.6,No,0.0,No
312,0.2,15.5,1.0,2.4,9.4,SE,31.0,NaN,WNW,0.0,...,37,1020.6,1018.2,1,1,7.2,15.3,No,0.0,No
348,11.9,21.1,13.2,6.6,NaN,NW,41.0,NNE,N,7.0,...,61,1019.2,1016.7,7,3,14.5,19.4,Yes,0.6,No
351,5.0,24.1,0.0,6.2,12.0,NNW,52.0,NaN,NNW,0.0,...,34,1024.5,1020.7,6,1,11.6,21.9,No,0.0,No
360,7.9,26.1,0.0,6.8,3.5,NNW,43.0,NaN,WNW,0.0,...,20,1017.6,1014.2,5,8,16.3,25.9,No,0.0,No

In [7]:
before_rows = data.shape[0]
print(before_rows)

366

In [8]:
after_rows = data.shape[0]
print(after_rows)

366

In [9]:
before_rows - after_rows

0

In [11]:
clean_data = data.copy()
humidity_level=24.99
clean_data['high_humidity_label'] = (clean_data['Humidity3pm'] > humidity_level)*1
print(clean_data['high_humidity_label'])

0      1
1      1
2      1
3      1
4      1
      ..
361    0
362    0
363    1
364    1
365    0
Name: high_humidity_label, Length: 366, dtype: int32

In [12]:
y=clean_data[['high_humidity_label']].copy()
y

     high_humidity_label
0                      1
1                      1
2                      1
3                      1
4                      1
..                   ...
361                    0
362                    0
363                    1
364                    1
365                    0

[366 rows x 1 columns]

In [14]:
y.head()

   high_humidity_label
0                    1
1                    1
2                    1
3                    1
4                    1

In [15]:
morning_features = ['WindDir9am','WindDir3pm','WindSpeed9am','Humidity3pm','Pressure9am','Pressure3pm','Cloud9am','Cloud3pm','Temp9am','Temp3pm']

In [16]:
X = clean_data[morning_features].copy()

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=324)

In [18]:
print(type(X_train),
type(X_test),
type(y_train),
type(y_test))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.frame.DataFrame'> <class 'pandas.core.frame.DataFrame'> <class 'pandas.core.frame.DataFrame'>

In [19]:
X_train.head()

,WindDir9am,WindDir3pm,WindSpeed9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
186,NE,WNW,2.0,41,1019.8,1015.8,6,5,7.7,18.5
80,NW,WNW,19.0,71,1004.9,1004.0,7,8,19.4,21.9
233,E,WNW,6.0,59,1023.0,1021.0,3,6,4.2,12.1
257,NaN,NNW,NaN,46,1023.0,1020.1,1,7,3.9,13.3
315,NE,N,4.0,20,1018.8,1013.9,1,1,6.0,16.3

In [21]:
y_train.head()

     high_humidity_label
186                    1
80                     1
233                    1
257                    1
315                    0

ValueError: could not convert string to float: 'NNW'